services:
  app:
    build: .
    ports:
      - "8045:8045"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app/src
      - ./output:/app/output
      - ./resources:/app/resources
      - ${APP_DIR:-./database}:/app/database
      # Mount cache directory to persist models
      - ~/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    command: uvicorn main:app --host 0.0.0.0 --port 8045
