site_name: Quisy TTS
site_url: https://your-username.github.io/quisy-tts/
repo_url: https://github.com/your-username/quisy-tts/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo

plugins:
  - search
  - plantuml:
      puml_url: http://www.plantuml.com/plantuml/svg/

nav:
  - Home: index.md
  - Architecture: arc42/01_introduction.md
